Connect-api
davidigbo/bookstore pull request #4
Opened 2023-04-15 05:28 UTC by david30-maker

In this pull request, I implement api for the bookstore application by following these steps:

-Make use of the [Bookstore API] 
-Use [axios](https://axios-http.com/docs/intro) with [createAsyncThunk](https://redux-toolkit.js.org/api/createAsyncThunk) to make your HTTP requests to the backend
-Fetch your books from the Bookstore API after the component has rendered
-Refactor your add book and remove book features to persist your changes in the server
-Your application should behave the same way after the refactoring

2023-04-15 06:09 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct . :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly fix the MIT License link on your README file. It is broken at this moment.

![license](https://user-images.githubusercontent.com/26597432/232188990-7221067c-deff-4153-ae56-c98a4c9354fe.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-15 06:09 UTC, Qoosim commented on src/components/bookItems.js
> +          <button
- [ ] The book prop you passed into the BookItem component is seen as being undefined. As a result there is an error that's preventing the app from loading on the browser. Kindly take a look and fix.

### Error on the browser
![error](https://user-images.githubusercontent.com/26597432/232188528-6c76f2f8-3ad6-442c-81e1-754c9a19b56f.png)

2023-04-15 07:05 UTC, david30-maker commented
Thanks for oyu reviewing my code, I will implement the changes

2023-04-15 12:01 UTC, Zuhaib042 requested changes
Hi @david30-maker  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![](https://media.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-15 12:01 UTC, Zuhaib042 commented on README.md
> +This project is [MIT](./LICENSE.md) licensed.
- [ ] As suggested by the previous reviewer, this link is still broken. The reason of this is that you don't have `LICENSE.md` file in your repo. kindly consider adding a LICENSE.md in your repo and then check if the link works before submitting it again.

2023-04-15 12:01 UTC, Zuhaib042 commented on src/components/bookItems.js
> +      <div className="book-detail">
- [ ] As suggested by the previous reviewer, The `book` prop in this `BookItem` component is `undefined`. This error is popping up in the browser so the app is not working. kindly consider fixing this bug before submitting it again.
the error in the browser
![qw](https://user-images.githubusercontent.com/96683843/232218881-e9efa3b3-937a-4768-bfae-3284c9b229e8.jpg)

2023-04-15 12:01 UTC, Zuhaib042 commented on src/components/bookItems.js
> +// export default BookItem;
- [OPTIONAL] Kindly consider removing this commented code as it makes our codebase messy and unprofessional.

2023-04-18 15:22 UTC, julie-ify requested changes
## Hi @david30-maker,

Good job so far!

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-18 15:22 UTC, julie-ify commented on README.md
> +This project is [MIT](./LICENSE.md) licensed.
- [ ] Kindly fix this issue of missing MIT link.

  ![image](https://user-images.githubusercontent.com/81468675/232824076-78ce9691-93ff-48ec-8d37-8179eb3225a4.png)

2023-04-18 16:09 UTC, julie-ify reviewed
Hi @david30-maker,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly fix the issue highlighted earlier (or push the changes). The MIT link on your readme file is still broken.

![image](https://user-images.githubusercontent.com/81468675/232837716-7a4bc30d-4015-4160-94c8-a1f69086d871.png)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-18 16:34 UTC, Davidosky007 reviewed
Hi @david30-maker 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a broken MIT link kindly fix this 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-18 17:40 UTC, TadesseDev approved these changes
### Hi @david30-maker 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy (1)](https://user-images.githubusercontent.com/69077061/212969210-69f495ba-f2fb-4559-a222-d1507310d6fb.gif)



## Highlights
 - [x] Good job making the changes requested by the previous code reviewer. ✅

## Optional suggestions
- [Optional] Please consider removing non-important contents from your readme, The template is designed by Microverse for us all to use to document our projects professionally and has it filled with content related to each project we may be working on. currently, I can see you have not removed the guiding contents  which start with `>` and `directions set by Microverser`

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-18 17:44 UTC, david30-maker commented
Thanks, @TadesseDev for reviewing my code

2023-04-18 17:44 UTC, merged